### ISSUE TITLE
What GPIO Pin does this use?

### ISSUE THREAD

**Issue by s3m1s0n1c** [amsross/node-talkiepi#3]

**Comment by amsross** [comment]
Just for reference to anyone else, the pins are all set here: https://github.com/amsross/node-talkiepi/blob/c499e1fb85fd88022ea4821348fe41d114aecb3f/lib/TalkiePi.js#L23-L29

It probably would have been more responsible to accept those pin values as params.

**Comment by s3m1s0n1c** [comment]
Thanks Amsross,

Would be also nice to have these in config where you can set these values also for servername & username..

Just a Idea 😄

**Comment by amsross** [comment]
If you're participating in [hacktoberfest](https://hacktoberfest.digitalocean.com/), I'd welcome PRs for both or either change.

At the same time, I'd argue that if all options are available as either CLI params or ENV vars, then a user can wrap those in a script/container/process and set them however they like.

For example, these arguments could default to `process.env.VAR_NAME`, which can be set via build process, container environment, etc:
https://github.com/amsross/node-talkiepi/blob/c499e1fb85fd88022ea4821348fe41d114aecb3f/options.js#L2-L5
